services:
  nuxt:
    container_name: nuxt
    build: docker
    volumes:
      - ./app:/app:cached # appディレクトリとappディレクトリをリンク
    ports:
      - "3333:3000" # (左側)ブラウザアクセス時のポート番号 (右側)コンテナ内のポート番号
    tty: true
    command: sh -c "npm install && npm run dev" # コンテナ起動時に自動でnuxtが起動する
